# Customer Support Data Analysis

## Introduction
This notebook analyzes customer support data obtained from Kaggle.com. The dataset captures various aspects of customer interactions, agent performance, and product-specific details. Our goal is to extract actionable insights to improve customer satisfaction, agent productivity, and operational efficiency.

## Dataset Overview
The dataset contains the following columns:

1. **Unique id**: A unique identifier for each record in the dataset.
2. **channel_name**: The communication channel used (e.g., Email, Chat, Call).
3. **category**: Broad categories of issues reported by customers (e.g., Billing, Technical, Delivery).
4. **Sub-category**: Specific sub-categories of the issues within each category.
5. **Customer Remarks**: Feedback provided by customers (e.g., "Good", "Reverse Return Request").
6. **Order_id**: Unique identifier for each customer order related to the case.
7. **order_date_time**: The date and time when the order was placed.
8. **Issue_reported at**: The timestamp of when the issue was reported.
9. **issue_responded**: Indicates whether the reported issue was responded to (Yes/No).
10. **Survey_response_Date**: The date when the customer completed the survey or provided feedback.
11. **Customer_City**: The city where the customer is located.
12. **Product_category**: The category of the product involved in the interaction (e.g., Electronics, Clothing).
13. **Item_price**: The price of the item associated with the order.
14. **connected_handling_time**: Total time spent by the agent to resolve the issue.
15. **Agent_name**: The name of the agent who handled the case.
16. **Supervisor**: The supervisor assigned to oversee the agent handling the case.
17. **Manager**: The manager responsible for the overall resolution process.
18. **Tenure Bucket**: Grouping of agents based on their tenure with the organization (e.g., 0-6 months, 6-12 months).
19. **Agent Shift**: The shift in which the agent worked during the case (e.g., Morning, Evening, Night).
20. **CSAT Score**: The customer satisfaction score provided by the customer (on a scale of 1 to 5).

## Purpose
This analysis aims to:
1. Identify patterns in customer feedback and satisfaction through metrics like CSAT Score.
2. Understand agent performance based on handling time and shift details.
3. Analyze issue trends across channels, categories, and sub-categories.
4. Identify product categories or price points associated with high customer dissatisfaction.
5. Evaluate operational aspects like response times, manager impact, and tenure influence.

In [13]:

import pandas as pd

# Load the dataset
data = pd.read_csv('Customer_support_data.csv')
data

,Unique id,channel_name,category,Sub-category,Customer Remarks,Order_id,order_date_time,Issue_reported at,issue_responded,Survey_response_Date,Customer_City,Product_category,Item_price,connected_handling_time,Agent_name,Supervisor,Manager,Tenure Bucket,Agent Shift,CSAT Score
0,7e9ae164-6a8b-4521-a2d4-58f7c9fff13f,Outcall,Product Queries,Life Insurance,NaN,c27c9bb4-fa36-4140-9f1f-21009254ffdb,NaN,01/08/2023 11:13,01/08/2023 11:47,01-Aug-23,NaN,NaN,NaN,NaN,Richard Buchanan,Mason Gupta,Jennifer Nguyen,On Job Training,Morning,5
1,b07ec1b0-f376-43b6-86df-ec03da3b2e16,Outcall,Product Queries,Product Specific Information,NaN,d406b0c7-ce17-4654-b9de-f08d421254bd,NaN,01/08/2023 12:52,01/08/2023 12:54,01-Aug-23,NaN,NaN,NaN,NaN,Vicki Collins,Dylan Kim,Michael Lee,>90,Morning,5
2,200814dd-27c7-4149-ba2b-bd3af3092880,Inbound,Order Related,Installation/demo,NaN,c273368d-b961-44cb-beaf-62d6fd6c00d5,NaN,01/08/2023 20:16,01/08/2023 20:38,01-Aug-23,NaN,NaN,NaN,NaN,Duane Norman,Jackson Park,William Kim,On Job Training,Evening,5
3,eb0d3e53-c1ca-42d3-8486-e42c8d622135,Inbound,Returns,Reverse Pickup Enquiry,NaN,5aed0059-55a4-4ec6-bb54-97942092020a,NaN,01/08/2023 20:56,01/08/2023 21:16,01-Aug-23,NaN,NaN,NaN,NaN,Patrick Flores,Olivia Wang,John Smith,>90,Evening,5
4,ba903143-1e54-406c-b969-46c52f92e5df,Inbound,Cancellation,Not Needed,NaN,e8bed5a9-6933-4aff-9dc6-ccefd7dcde59,NaN,01/08/2023 10:30,01/08/2023 10:32,01-Aug-23,NaN,NaN,NaN,NaN,Christopher Sanchez,Austin Johnson,Michael Lee,0-30,Morning,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85902,505ea5e7-c475-4fac-ac36-1d19a4cb610f,Inbound,Refund Related,Refund Enquiry,NaN,1b5a2b9c-a95f-405f-a42e-5b1b693f3dc9,NaN,30/08/2023 23:20,31/08/2023 07:22,31-Aug-23,NaN,NaN,NaN,NaN,Brandon Leon,Ethan Tan,William Kim,On Job Training,Morning,4
85903,44b38d3f-1523-4182-aba2-72917586647c,Inbound,Order Related,Seller Cancelled Order,Supported team customer executive good,d0e8a817-96d5-4ace-bb82-adec50398e22,NaN,31/08/2023 08:15,31/08/2023 08:17,31-Aug-23,NaN,NaN,NaN,NaN,Linda Foster,Noah Patel,Emily Chen,>90,Morning,5
85904,723bce2c-496c-4aa8-a64b-ca17004528f0,Inbound,Order Related,Order status enquiry,need to improve with proper details.,bdefe788-ccec-4eda-8ca4-51045e68db8a,NaN,31/08/2023 18:57,31/08/2023 19:02,31-Aug-23,NaN,NaN,NaN,NaN,Kimberly Martinez,Aiden Patel,Olivia Tan,On Job Training,Evening,5
85905,707528ee-6873-4192-bfa9-a491f1c08ab5,Inbound,Feedback,UnProfessional Behaviour,NaN,a031ec28-0c5e-450e-95b2-592342c40bc4,NaN,31/08/2023 19:59,31/08/2023 20:00,31-Aug-23,NaN,NaN,NaN,NaN,Daniel Martin,Olivia Suzuki,Olivia Tan,>90,Morning,4
85906,07c7a878-0d5a-42e0-97ef-de59abec0238,Inbound,Returns,Reverse Pickup Enquiry,NaN,3230db30-f8da-4c44-8636-ec76d1d3d4f3,NaN,31/08/2023 23:36,31/08/2023 23:37,31-Aug-23,NaN,NaN,NaN,NaN,Elizabeth Guerra,Nathan Patel,Jennifer Nguyen,On Job Training,Evening,5

## Dataset Overview

In [14]:
# print("Dataset Overview:")
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85907 entries, 0 to 85906
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unique id                85907 non-null  object
 1   channel_name             85907 non-null  object
 2   category                 85907 non-null  object
 3   Sub-category             85907 non-null  object
 4   Customer Remarks         28742 non-null  object
 5   Order_id                 67675 non-null  object
 6   order_date_time          17214 non-null  object
 7   Issue_reported at        85907 non-null  object
 8   issue_responded          85907 non-null  object
 9   Survey_response_Date     85907 non-null  object
 10  Customer_City            17079 non-null  object
 11  Product_category         17196 non-null  object
 12  Item_price               17206 non-null  float64
 13  connected_handling_time  242 non-null    float64
 14  Agent_name               85907 non-null  object
 15  Supervisor               85907 non-null  object
 16  Manager                  85907 non-null  object
 17  Tenure Bucket            85907 non-null  object
 18  Agent Shift              85907 non-null  object
 19  CSAT Score               85907 non-null  int64
dtypes: float64(2), int64(1), object(17)
memory usage: 13.1+ MB
None

## Column Names in the Dataset

In [15]:
data.columns

Index(['Unique id', 'channel_name', 'category', 'Sub-category',
       'Customer Remarks', 'Order_id', 'order_date_time', 'Issue_reported at',
       'issue_responded', 'Survey_response_Date', 'Customer_City',
       'Product_category', 'Item_price', 'connected_handling_time',
       'Agent_name', 'Supervisor', 'Manager', 'Tenure Bucket', 'Agent Shift',
       'CSAT Score'],
      dtype='object')

## Previewing the Dataset

In [16]:
data.head()

,Unique id,channel_name,category,Sub-category,Customer Remarks,Order_id,order_date_time,Issue_reported at,issue_responded,Survey_response_Date,Customer_City,Product_category,Item_price,connected_handling_time,Agent_name,Supervisor,Manager,Tenure Bucket,Agent Shift,CSAT Score
0,7e9ae164-6a8b-4521-a2d4-58f7c9fff13f,Outcall,Product Queries,Life Insurance,NaN,c27c9bb4-fa36-4140-9f1f-21009254ffdb,NaN,01/08/2023 11:13,01/08/2023 11:47,01-Aug-23,NaN,NaN,NaN,NaN,Richard Buchanan,Mason Gupta,Jennifer Nguyen,On Job Training,Morning,5
1,b07ec1b0-f376-43b6-86df-ec03da3b2e16,Outcall,Product Queries,Product Specific Information,NaN,d406b0c7-ce17-4654-b9de-f08d421254bd,NaN,01/08/2023 12:52,01/08/2023 12:54,01-Aug-23,NaN,NaN,NaN,NaN,Vicki Collins,Dylan Kim,Michael Lee,>90,Morning,5
2,200814dd-27c7-4149-ba2b-bd3af3092880,Inbound,Order Related,Installation/demo,NaN,c273368d-b961-44cb-beaf-62d6fd6c00d5,NaN,01/08/2023 20:16,01/08/2023 20:38,01-Aug-23,NaN,NaN,NaN,NaN,Duane Norman,Jackson Park,William Kim,On Job Training,Evening,5
3,eb0d3e53-c1ca-42d3-8486-e42c8d622135,Inbound,Returns,Reverse Pickup Enquiry,NaN,5aed0059-55a4-4ec6-bb54-97942092020a,NaN,01/08/2023 20:56,01/08/2023 21:16,01-Aug-23,NaN,NaN,NaN,NaN,Patrick Flores,Olivia Wang,John Smith,>90,Evening,5
4,ba903143-1e54-406c-b969-46c52f92e5df,Inbound,Cancellation,Not Needed,NaN,e8bed5a9-6933-4aff-9dc6-ccefd7dcde59,NaN,01/08/2023 10:30,01/08/2023 10:32,01-Aug-23,NaN,NaN,NaN,NaN,Christopher Sanchez,Austin Johnson,Michael Lee,0-30,Morning,5

## Summary Statistics

In [17]:
print("Summary Statistics:")
print(data.describe())

Summary Statistics:
          Item_price  connected_handling_time    CSAT Score
count   17206.000000               242.000000  85907.000000
mean     5660.774846               462.400826      4.242157
std     12825.728411               246.295037      1.378903
min         0.000000                 0.000000      1.000000
25%       392.000000               293.000000      4.000000
50%       979.000000               427.000000      5.000000
75%      2699.750000               592.250000      5.000000
max    164999.000000              1986.000000      5.000000

## Random Sampling from the Dataset

In [18]:
data.sample()

,Unique id,channel_name,category,Sub-category,Customer Remarks,Order_id,order_date_time,Issue_reported at,issue_responded,Survey_response_Date,Customer_City,Product_category,Item_price,connected_handling_time,Agent_name,Supervisor,Manager,Tenure Bucket,Agent Shift,CSAT Score
459,f322c85f-a16c-4825-a279-3dcdc4c96dea,Inbound,Order Related,Priority delivery,very helpful,a61037e8-9766-4fa0-8492-e44142bd7ef7,29/07/2023 09:32,31/07/2023 19:25,01/08/2023 08:24,01-Aug-23,PALAKKAD,Mobile,44720.0,NaN,Wendy Anderson,Harper Wong,William Kim,On Job Training,Evening,5

## Checking for Missing Values

In [19]:
print("Missing Values Per Column:")
print(data.isnull().sum())

Missing Values Per Column:
Unique id                      0
channel_name                   0
category                       0
Sub-category                   0
Customer Remarks           57165
Order_id                   18232
order_date_time            68693
Issue_reported at              0
issue_responded                0
Survey_response_Date           0
Customer_City              68828
Product_category           68711
Item_price                 68701
connected_handling_time    85665
Agent_name                     0
Supervisor                     0
Manager                        0
Tenure Bucket                  0
Agent Shift                    0
CSAT Score                     0
dtype: int64

## Finding the Most Purchased Product Category

In [20]:
category_counts = data['Product_category'].value_counts()

# Find the most purchased product category
most_bought_category = category_counts.idxmax()
most_bought_count = category_counts.max()

print(f"The most purchased product category is '{most_bought_category}' with {most_bought_count} purchases.")

The most purchased product category is 'Electronics' with 4706 purchases.

## Analyzing "Reverse Return Request" Remarks by Product Category

In [21]:


# Filter rows with "Reverse Return Request" in customer remarks
filtered_data = data[data['category'] == 'Returns']

# Group by product category and count occurrences
category_counts = filtered_data['Product_category'].value_counts()

# Find the product category with the maximum count
max_category = category_counts.idxmax()# Find index of the maximum value

max_count = category_counts.max()

print(f"The product category with the most 'Reverse Return Request' remarks is '{max_category}' with {max_count} requests.")

The product category with the most 'Reverse Return Request' remarks is 'Electronics' with 2782 requests.

## Analyzing Missing Values in 'Customer_City' Column

In [22]:
null_count = data['Customer_City'].isnull().sum()
total_rows = len(data)

print(f"Number of null values in 'Customer_City': {null_count}")
print(f"Percentage of null values: {(null_count / total_rows) * 100:.2f}%")

Number of null values in 'Customer_City': 68828
Percentage of null values: 80.12%

## Identifying the Most Common Customer Remark

In [23]:
remark_counts = data['Customer Remarks'].value_counts()

# Find the most common remark
most_common_remark = remark_counts.idxmax()
most_common_count = remark_counts.max()

print(f"The most common customer remark is '{most_common_remark}' with {most_common_count} occurrences.")

The most common customer remark is 'Good ' with 1390 occurrences.

## Filtering Reviews Excluding 'Good'

In [24]:
filtered_reviews = data[data['Customer Remarks'] != 'Good']

# Display the filtered data
print("Reviews excluding 'Good':")
filtered_reviews

Reviews excluding 'Good':

,Unique id,channel_name,category,Sub-category,Customer Remarks,Order_id,order_date_time,Issue_reported at,issue_responded,Survey_response_Date,Customer_City,Product_category,Item_price,connected_handling_time,Agent_name,Supervisor,Manager,Tenure Bucket,Agent Shift,CSAT Score
0,7e9ae164-6a8b-4521-a2d4-58f7c9fff13f,Outcall,Product Queries,Life Insurance,NaN,c27c9bb4-fa36-4140-9f1f-21009254ffdb,NaN,01/08/2023 11:13,01/08/2023 11:47,01-Aug-23,NaN,NaN,NaN,NaN,Richard Buchanan,Mason Gupta,Jennifer Nguyen,On Job Training,Morning,5
1,b07ec1b0-f376-43b6-86df-ec03da3b2e16,Outcall,Product Queries,Product Specific Information,NaN,d406b0c7-ce17-4654-b9de-f08d421254bd,NaN,01/08/2023 12:52,01/08/2023 12:54,01-Aug-23,NaN,NaN,NaN,NaN,Vicki Collins,Dylan Kim,Michael Lee,>90,Morning,5
2,200814dd-27c7-4149-ba2b-bd3af3092880,Inbound,Order Related,Installation/demo,NaN,c273368d-b961-44cb-beaf-62d6fd6c00d5,NaN,01/08/2023 20:16,01/08/2023 20:38,01-Aug-23,NaN,NaN,NaN,NaN,Duane Norman,Jackson Park,William Kim,On Job Training,Evening,5
3,eb0d3e53-c1ca-42d3-8486-e42c8d622135,Inbound,Returns,Reverse Pickup Enquiry,NaN,5aed0059-55a4-4ec6-bb54-97942092020a,NaN,01/08/2023 20:56,01/08/2023 21:16,01-Aug-23,NaN,NaN,NaN,NaN,Patrick Flores,Olivia Wang,John Smith,>90,Evening,5
4,ba903143-1e54-406c-b969-46c52f92e5df,Inbound,Cancellation,Not Needed,NaN,e8bed5a9-6933-4aff-9dc6-ccefd7dcde59,NaN,01/08/2023 10:30,01/08/2023 10:32,01-Aug-23,NaN,NaN,NaN,NaN,Christopher Sanchez,Austin Johnson,Michael Lee,0-30,Morning,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85902,505ea5e7-c475-4fac-ac36-1d19a4cb610f,Inbound,Refund Related,Refund Enquiry,NaN,1b5a2b9c-a95f-405f-a42e-5b1b693f3dc9,NaN,30/08/2023 23:20,31/08/2023 07:22,31-Aug-23,NaN,NaN,NaN,NaN,Brandon Leon,Ethan Tan,William Kim,On Job Training,Morning,4
85903,44b38d3f-1523-4182-aba2-72917586647c,Inbound,Order Related,Seller Cancelled Order,Supported team customer executive good,d0e8a817-96d5-4ace-bb82-adec50398e22,NaN,31/08/2023 08:15,31/08/2023 08:17,31-Aug-23,NaN,NaN,NaN,NaN,Linda Foster,Noah Patel,Emily Chen,>90,Morning,5
85904,723bce2c-496c-4aa8-a64b-ca17004528f0,Inbound,Order Related,Order status enquiry,need to improve with proper details.,bdefe788-ccec-4eda-8ca4-51045e68db8a,NaN,31/08/2023 18:57,31/08/2023 19:02,31-Aug-23,NaN,NaN,NaN,NaN,Kimberly Martinez,Aiden Patel,Olivia Tan,On Job Training,Evening,5
85905,707528ee-6873-4192-bfa9-a491f1c08ab5,Inbound,Feedback,UnProfessional Behaviour,NaN,a031ec28-0c5e-450e-95b2-592342c40bc4,NaN,31/08/2023 19:59,31/08/2023 20:00,31-Aug-23,NaN,NaN,NaN,NaN,Daniel Martin,Olivia Suzuki,Olivia Tan,>90,Morning,4
85906,07c7a878-0d5a-42e0-97ef-de59abec0238,Inbound,Returns,Reverse Pickup Enquiry,NaN,3230db30-f8da-4c44-8636-ec76d1d3d4f3,NaN,31/08/2023 23:36,31/08/2023 23:37,31-Aug-23,NaN,NaN,NaN,NaN,Elizabeth Guerra,Nathan Patel,Jennifer Nguyen,On Job Training,Evening,5

## Removing Rows with Missing Values

In [17]:
cleaned_data = data.dropna()

print("Rows with NaN values removed:")
print(cleaned_data)

Rows with NaN values removed:
                                  Unique id channel_name       category  \
13565  08c6a929-a403-4f14-810f-2275fe591230      Outcall        Returns
13603  eae37bb3-91ec-4154-ba3c-7e4a6309a946      Outcall        Returns
18445  296c5c93-6a4f-4fa5-b276-3feecfeaf636      Outcall        Returns
19678  5155d369-7bc3-4c40-9e26-6dcee58ace99      Outcall        Returns
20080  ddaae943-3535-452e-857f-591d4b9ae0c8      Outcall   Cancellation
20363  00c52c83-d40a-4b0f-80ea-fcffe23cef76      Outcall        Returns
20439  5b3a9dfe-8c26-4c5f-9824-02db5daf7ecb      Outcall        Returns
22514  8d093faf-8359-494d-9955-224cf8a5de8d      Outcall        Returns
26301  150a36e8-48bc-47d2-bce6-436b65d2fab8      Outcall        Returns
26387  1c0c98aa-2fdc-4899-af96-de7cbec1977c      Outcall        Returns
26499  43efcc9f-7143-4895-8ffe-e50421ee8b00      Outcall        Returns
26661  891fd7e5-59a5-43f9-9b1c-cf9b2e14b14e      Outcall        Returns
26708  82d615a4-6731-4a79-84b7-2bdb42e2c4dc      Outcall        Returns
27104  821583b1-48d9-40bb-849c-a32b0382d1fc      Outcall        Returns
27141  b4c7ceea-92d5-4f75-81aa-4e0a129ee638      Outcall        Returns
28193  22df64f7-2530-46e1-ba58-fee4265802f5      Outcall        Returns
28808  bc34a27a-bf19-4132-9629-88b09a9b6e2a      Outcall        Returns
28920  75bc0360-b5c6-4566-9880-24d5681f2de6      Outcall        Returns
29365  07030f1f-84c9-493c-a8a3-159f6d58ebc9      Outcall   Cancellation
31681  f5b74aa2-934d-4d44-a9aa-db68f42fc1c3      Outcall        Returns
31697  b9d109b9-35fa-40b2-a358-8ef83ac47bda      Outcall   Cancellation
33336  abf385db-925e-44c5-8112-a4399b61716c      Outcall        Returns
34544  7f55a2c1-9e16-4dd4-aa1c-8c28b40e02e0      Outcall   Cancellation
37420  28c46a62-2be4-401b-b73c-2c68486dd5cc      Outcall        Returns
37501  ee67e456-4cc1-40a4-9253-d1ecca814030      Outcall        Returns
37808  27c2659e-df10-4bac-af87-da3fae75a8b2      Outcall        Returns
38925  f5b9f8d9-05d1-4e67-b5dd-01b37b0a71b6      Outcall        Returns
39732  473de3fb-934b-4dd4-8f9d-91559ce291a8      Outcall        Returns
46703  ce3a498d-727a-4378-9b2f-519fb1e85c12      Outcall        Returns
46972  98105df6-15f2-4e73-a593-38138e4fdee4      Outcall        Returns
47532  66b067d8-cbb0-4d92-ad94-9b9fc760e269      Outcall        Returns
47745  89b8ba13-fa38-4ed9-8c67-b0ee610cac30      Outcall        Returns
48034  7905b6ac-e5c0-45e5-a71c-989d6050ceef      Outcall        Returns
48313  94e83ff7-d920-4b6c-a590-afadb71f85e4      Outcall        Returns
48710  f9af8085-e991-4205-8804-caefe6194040      Outcall        Returns
49018  b6501670-1fcc-49cb-8ab6-95fd411fc851      Outcall        Returns
55265  d1a52873-389a-4ad3-8043-7480181bda2a      Outcall        Returns
85016  2adb7651-c900-43b9-a539-d8f1d64df3c5      Inbound  Order Related

               Sub-category  \
13565        Return request
13603        Return request
18445        Return request
19678        Return request
20080   Return cancellation
20363        Return request
20439        Return request
22514        Return request
26301        Return request
26387        Return request
26499        Return request
26661        Return request
26708        Return request
27104        Return request
27141        Return request
28193        Return request
28808        Return request
28920        Return request
29365   Return cancellation
31681        Return request
31697   Return cancellation
33336        Return request
34544   Return cancellation
37420        Return request
37501        Return request
37808        Return request
38925        Return request
39732        Return request
46703        Return request
46972        Return request
47532        Return request
47745        Return request
48034        Return request
48313        Return request
48710        Return request
49018        Return request
55265        Return request
85016  Order status enquiry

                                        Customer Remarks  \
13565                                               Good
13603                                          Not good
18445                                  Call was helpful.
19678                                       Good service
20080                                            Thanks
20363                                           Good job
20439                                Super customer care
22514                         Very genuine person ??????
26301  Product is not best.delivery good.costmor care...
26387                              Shopzilla Is the Best
26499                                               Good
26661                                          Thankyou
26708  Product delivery time shuld be fast.Otherwise ...
27104       plz allow return policy for all the products
27141                                Very very Excellent
28193                        nothing every thing is good
28808                    Good girl ache se bath ki waaoo
28920  Thanku so much for resolving my problem thanks...
29365                                         Thank you
31681                                         Excellent
31697  The lady executive was very polite and I was h...
33336                                           Happy ??
34544                             THANK YOU Shopzilla ??
37420                               Service is very good
37501                                         Satishfied
37808                                                No
38925  Shopzilla should provide all good equipments ....
39732                 Great experience in solving issue
46703                                              Good
46972                    Apse bat karke bahot hi   apka
47532                                         Very nice
47745                                          It's good
48034                                         Excellent
48313                                               Good
48710           Only one request time is more important
49018                                         Excellent
55265                                      good services
85016  Sir apse muze koi dikkat nhi hai but apka cust...

                                   Order_id   order_date_time  \
13565  0258d703-8287-428d-9e48-446e29eec3e5  29/07/2023 03:44
13603  d5d704c1-7d8e-4573-8e9d-aec29e6d3b40  31/07/2023 20:21
18445  6a318938-1b06-4394-82d7-83a0d7c18f29  29/07/2023 22:52
19678  feb6c5f8-5418-4abc-aec4-494ce0df2791  01/08/2023 13:35
20080  68b1ae3c-a0f9-48c7-96f0-2e17a460814c  03/08/2023 13:42
20363  8f14a636-094a-4810-8d61-c14b2478c9bd  30/07/2023 18:10
20439  fe85b0a1-5abb-4f02-8750-61937e039bfd  04/08/2023 00:03
22514  9c7ac0e3-2c31-42d6-903e-ad11439ed523  03/08/2023 15:52
26301  f89b47a1-c44e-48bd-98d8-037db0ee5d53  21/07/2023 20:12
26387  9e94dd00-4e52-4389-91c2-646027ad8680  03/08/2023 11:00
26499  6b41d7d0-e746-4a89-b56e-e48704ce111e  05/08/2023 00:40
26661  70c121f6-73ee-438c-a8a1-c2debb9f1b30  25/07/2023 14:28
26708  a22e098c-72ed-4a12-8348-b9a626361cde  04/08/2023 16:55
27104  7c772843-f137-45aa-bbe2-e2d4bf8a1029  03/08/2023 12:05
27141  4389d91b-e040-4322-99d8-b9e6549f23b9  07/08/2023 10:47
28193  9ee09e99-97a4-4713-8cb1-2d8cf07c41d1  02/08/2023 14:26
28808  63f549dd-1f99-4a1d-9be8-4d2de4040cce  03/08/2023 14:30
28920  40086ff4-4a4b-4f97-ac50-2aaca7da9571  06/08/2023 16:26
29365  8baa3add-355d-491d-8f4c-25ad4f5f4d03  01/08/2023 10:48
31681  29313068-1c8e-4253-9ea4-44a5419da215  03/08/2023 09:48
31697  155b8e74-98d3-48f8-890e-2b4888905dcd  05/08/2023 12:07
33336  a5e11d88-27f0-49c0-adc2-2b9c776d269c  04/08/2023 08:51
34544  a5c8d130-0005-4aa1-b3d8-0ce5144ae6c5  08/08/2023 09:03
37420  e16cbbea-80e5-4387-a407-2043d70ff80b  03/08/2023 10:46
37501  6d9a1662-fb09-4937-b288-6d3cb659d03e  05/08/2023 17:52
37808  107f7d8a-6126-4c7b-8680-4fdc1a80fd30  09/08/2023 11:57
38925  4660b47e-c6ec-4cf0-9b05-56c9386fe99d  03/08/2023 19:11
39732  44f1503a-3f73-44eb-a311-d7584df3b815  07/08/2023 21:29
46703  eadb0b0e-4c5c-4105-a458-f0ad7a1f0b1d  09/08/2023 12:45
46972  d7dc9ec3-c5e4-4f30-b1fa-54ca1545c4e5  06/08/2023 10:13
47532  73cf3e01-19dd-4747-b1da-edb624639e62  04/08/2023 23:05
47745  28b67f05-6f59-4d63-a873-d49396a9e87b  13/08/2023 22:07
48034  025b5c51-2942-4404-9bfd-27263cb3c829  01/08/2023 21:16
48313  0b9e04b3-50d8-473c-bc58-3b0269ed8034  05/08/2023 17:37
48710  63e80be2-2f80-4c8c-b516-2166d759f92f  06/08/2023 12:02
49018  4f863da4-fd0b-4ad0-ab2f-a7ad93a20157  08/08/2023 21:50
55265  297dc352-e97d-4687-b8f6-ba2fa0620488  26/07/2023 14:28
85016  3af034d2-a0ac-4693-8d2f-4c21901ef4e1  12/08/2023 06:49

      Issue_reported at   issue_responded Survey_response_Date Customer_City  \
13565  05/08/2023 11:11  05/08/2023 11:50            05-Aug-23       BETTIAH
13603  04/08/2023 12:04  05/08/2023 07:02            05-Aug-23         PATNA
18445  09/08/2023 12:40  09/08/2023 12:43            09-Aug-23          AGRA
19678  08/08/2023 12:35  08/08/2023 12:39            08-Aug-23       Birbhum
20080  07/08/2023 13:55  08/08/2023 09:21            08-Aug-23      BAREILLY
20363  08/08/2023 11:13  08/08/2023 16:01            08-Aug-23         BASTI
20439  08/08/2023 11:03  08/08/2023 11:07            08-Aug-23     MADHUGIRI
22514  08/08/2023 15:29  08/08/2023 15:32            08-Aug-23     BALESHWAR
26301  11/08/2023 19:38  11/08/2023 19:53            11-Aug-23        GOHANA
26387  11/08/2023 12:52  11/08/2023 12:56            11-Aug-23    BERHAMPORE
26499  11/08/2023 18:20  11/08/2023 19:47            11-Aug-23        MUMBAI
26661  12/08/2023 10:40  12/08/2023 10:44            12-Aug-23         ANAND
26708  12/08/2023 10:16  12/08/2023 12:17            12-Aug-23       BARASAT
27104  11/08/2023 10:26  11/08/2023 10:37            11-Aug-23        MAPUSA
27141  11/08/2023 10:06  11/08/2023 10:40            11-Aug-23       BARASAT
28193  11/08/2023 11:01  11/08/2023 11:41            11-Aug-23         PATNA
28808  11/08/2023 13:09  11/08/2023 13:13            11-Aug-23        BARMER
28920  12/08/2023 10:33  12/08/2023 10:53            12-Aug-23         VIRAR
29365  11/08/2023 15:21  11/08/2023 17:19            11-Aug-23      VADODARA
31681  10/08/2023 12:33  12/08/2023 11:15            12-Aug-23          PURI
31697  11/08/2023 10:59  11/08/2023 11:09            11-Aug-23   BHUBANESWAR
33336  11/08/2023 20:20  11/08/2023 20:29            11-Aug-23      PANIKOII
34544  11/08/2023 10:33  11/08/2023 10:36            11-Aug-23     NEW DELHI
37420  14/08/2023 13:35  14/08/2023 14:22            14-Aug-23      MAHESANA
37501  14/08/2023 17:42  14/08/2023 17:45            14-Aug-23     NAGERCOIL
37808  14/08/2023 18:07  14/08/2023 19:34            14-Aug-23         SALON
38925  14/08/2023 13:49  14/08/2023 13:52            14-Aug-23       NALBARI
39732  14/08/2023 18:07  14/08/2023 18:10            14-Aug-23       BAGHPAT
46703  18/08/2023 19:12  18/08/2023 19:16            18-Aug-23       ROORKEE
46972  17/08/2023 15:46  18/08/2023 10:44            18-Aug-23      RAYAGADA
47532  18/08/2023 12:33  18/08/2023 12:37            18-Aug-23      NEEMRANA
47745  18/08/2023 15:53  18/08/2023 15:58            18-Aug-23      NAMAKKAL
48034  18/08/2023 11:01  18/08/2023 11:03            18-Aug-23        MUMBAI
48313  18/08/2023 16:28  18/08/2023 16:39            18-Aug-23       KURNOOL
48710  18/08/2023 11:48  18/08/2023 11:50            18-Aug-23       DEOGHAR
49018  18/08/2023 18:43  18/08/2023 19:00            18-Aug-23     GHAZIABAD
55265  19/08/2023 14:11  21/08/2023 14:14            21-Aug-23          MOGA
85016  31/08/2023 20:46  31/08/2023 21:17            31-Aug-23      SRINAGAR

      Product_category  Item_price  connected_handling_time  \
13565      Electronics       899.0                    367.0
13603      Electronics       899.0                    604.0
18445      Electronics       868.0                    233.0
19678      Electronics       899.0                    458.0
20080      Electronics       799.0                    362.0
20363      Electronics       699.0                    384.0
20439      Electronics       899.0                    655.0
22514      Electronics       899.0                    460.0
26301      Electronics       899.0                    429.0
26387      Electronics       799.0                    217.0
26499      Electronics       679.0                    557.0
26661      Electronics       899.0                    418.0
26708      Electronics       799.0                    466.0
27104      Electronics       999.0                    467.0
27141      Electronics       799.0                    509.0
28193      Electronics       700.0                    253.0
28808      Electronics       999.0                    319.0
28920      Electronics       999.0                    221.0
29365      Electronics       999.0                    454.0
31681  Home Appliences       869.0                    368.0
31697      Electronics       999.0                    304.0
33336      Electronics       999.0                    721.0
34544      Electronics       999.0                    265.0
37420      Electronics       999.0                    732.0
37501  Home Appliences       924.0                    301.0
37808      Electronics       899.0                    361.0
38925  Home Appliences       999.0                    301.0
39732      Electronics       999.0                    398.0
46703      Electronics       899.0                     45.0
46972      Electronics       775.0                    413.0
47532      Electronics       643.0                    227.0
47745      Electronics       699.0                    343.0
48034      Electronics       899.0                    282.0
48313      Electronics       899.0                    299.0
48710      Electronics       899.0                    312.0
49018      Electronics       899.0                    216.0
55265      Electronics       799.0                    364.0
85016        LifeStyle       999.0                    505.0

                 Agent_name        Supervisor          Manager  \
13565        Katelyn Horton       Mason Gupta       Olivia Tan
13603          Michael Ruiz       Madison Kim       John Smith
18445         Dillon Miller       Mason Gupta       Olivia Tan
19678         Dillon Miller       Mason Gupta       Olivia Tan
20080        Patricia Cross       Mason Gupta       Olivia Tan
20363           Daniel Ball    Ethan Nakamura       Olivia Tan
20439       Evelyn Petersen       Olivia Wang       Olivia Tan
22514  Christopher Anderson       Mason Gupta       Olivia Tan
26301        Patricia Cross       Mason Gupta       Olivia Tan
26387        Michael Dunlap  Charlotte Suzuki  Jennifer Nguyen
26499          Mary Vasquez       Olivia Wang       Olivia Tan
26661          Teresa Nolan          Ava Wong       Olivia Tan
26708     Kathleen Williams       Mason Gupta       Olivia Tan
27104          Devon Daniel       Olivia Wang       Olivia Tan
27141          Mary Vasquez       Olivia Wang       Olivia Tan
28193           Tammy Rojas         Mia Patel       Olivia Tan
28808         Tammy Cochran       Madison Kim       John Smith
28920           James Chung     Oliver Nguyen       John Smith
29365          Edward Perez       Olivia Wang       Olivia Tan
31681         Erik Williams         Mia Patel       Olivia Tan
31697          Edward Perez       Olivia Wang       Olivia Tan
33336        Timothy Bailey       Mason Gupta       Olivia Tan
34544        Michael Dunlap  Charlotte Suzuki  Jennifer Nguyen
37420              Sean Gay         Mia Patel       Olivia Tan
37501        Jennifer Perry         Mia Patel       Olivia Tan
37808    Nicole Simpson DVM       Mason Gupta       Olivia Tan
38925        Timothy Bailey       Mason Gupta       Olivia Tan
39732     Kathleen Williams       Mason Gupta       Olivia Tan
46703       Jessica Mcbride       Olivia Wang       Olivia Tan
46972             Bob Keith         Mia Patel       Olivia Tan
47532        Timothy Bailey       Mason Gupta       Olivia Tan
47745    Nicole Simpson DVM       Mason Gupta       Olivia Tan
48034        Jennifer Perry         Mia Patel       Olivia Tan
48313           Tammy Rojas         Mia Patel       Olivia Tan
48710           Tammy Rojas         Mia Patel       Olivia Tan
49018        Jennifer Perry         Mia Patel       Olivia Tan
55265        Jennifer Perry         Mia Patel       Olivia Tan
85016            John Jones       Aiden Patel       John Smith

         Tenure Bucket Agent Shift  CSAT Score
13565             0-30     Morning           5
13603              >90     Morning           2
18445             0-30     Morning           4
19678             0-30     Morning           5
20080             0-30   Afternoon           5
20363              >90     Morning           5
20439             0-30     Morning           5
22514             0-30   Afternoon           5
26301             0-30   Afternoon           4
26387  On Job Training     Evening           5
26499             0-30     Morning           5
26661              >90     Morning           5
26708              >90     Morning           5
27104             0-30   Afternoon           5
27141             0-30     Morning           5
28193              >90     Morning           5
28808              >90       Split           5
28920              >90     Morning           5
29365              >90     Morning           4
31681              >90     Morning           5
31697              >90     Morning           5
33336              >90   Afternoon           5
34544  On Job Training     Evening           5
37420              >90     Morning           5
37501              >90     Morning           4
37808              >90     Morning           5
38925              >90   Afternoon           5
39732              >90     Morning           5
46703             0-30   Afternoon           5
46972             0-30   Afternoon           5
47532              >90   Afternoon           5
47745              >90     Morning           5
48034              >90     Morning           1
48313              >90     Morning           3
48710              >90     Morning           4
49018              >90     Morning           5
55265              >90     Morning           4
85016              >90     Morning           4

In [18]:
cleaned_data = data.dropna()
selected_columns = cleaned_data[['Product_category', 'Customer Remarks']]

# Print only selected columns
print("Selected Columns:")
selected_columns

Selected Columns:

      Product_category                                   Customer Remarks
13565      Electronics                                               Good
13603      Electronics                                          Not good
18445      Electronics                                  Call was helpful.
19678      Electronics                                       Good service
20080      Electronics                                            Thanks
20363      Electronics                                           Good job
20439      Electronics                                Super customer care
22514      Electronics                         Very genuine person ??????
26301      Electronics  Product is not best.delivery good.costmor care...
26387      Electronics                              Shopzilla Is the Best
26499      Electronics                                               Good
26661      Electronics                                          Thankyou
26708      Electronics  Product delivery time shuld be fast.Otherwise ...
27104      Electronics       plz allow return policy for all the products
27141      Electronics                                Very very Excellent
28193      Electronics                        nothing every thing is good
28808      Electronics                    Good girl ache se bath ki waaoo
28920      Electronics  Thanku so much for resolving my problem thanks...
29365      Electronics                                         Thank you
31681  Home Appliences                                         Excellent
31697      Electronics  The lady executive was very polite and I was h...
33336      Electronics                                           Happy ??
34544      Electronics                             THANK YOU Shopzilla ??
37420      Electronics                               Service is very good
37501  Home Appliences                                         Satishfied
37808      Electronics                                                No
38925  Home Appliences  Shopzilla should provide all good equipments ....
39732      Electronics                 Great experience in solving issue
46703      Electronics                                              Good
46972      Electronics                    Apse bat karke bahot hi   apka
47532      Electronics                                         Very nice
47745      Electronics                                          It's good
48034      Electronics                                         Excellent
48313      Electronics                                               Good
48710      Electronics           Only one request time is more important
49018      Electronics                                         Excellent
55265      Electronics                                      good services
85016        LifeStyle  Sir apse muze koi dikkat nhi hai but apka cust...



# Filter satisfied customers

In [19]:
satisfied_threshold = 4

# Filter satisfied customers
satisfied_customers = data[data['CSAT Score'] >= satisfied_threshold]

# Calculate CSAT score
total_responses = len(data['CSAT Score'])
satisfied_count = len(satisfied_customers)

# CSAT Score Formula
csat_score = (satisfied_count / total_responses) * 100

print(f"Total Responses: {total_responses}")
print(f"Satisfied Customers: {satisfied_count}")
print(f"CSAT Score: {csat_score:.2f}%")

Total Responses: 85907
Satisfied Customers: 70836
CSAT Score: 82.46%

## Identifying the Agent with the Maximum Work

In [20]:
agent_work = data.groupby('Agent_name')['connected_handling_time'].sum()

# Find the agent who has done the maximum work
max_work_agent = agent_work.idxmax()  # Agent name
max_work_time = agent_work.max()      # Total handling time

print(f"The agent who has done the maximum work is '{max_work_agent}' with a total handling time of {max_work_time}.")

The agent who has done the maximum work is 'Mary Vasquez' with a total handling time of 7107.0.